config/routes.rb
Rails.application.routes.draw do
  resources :notepads

  resources :specializations

  resources :medical_consultations

  resources :doctors

  root 'welcome#index'

  resources :users

  get  "users/index"
  get  "/login"           => "users#login"
  post "/signin"          => "users#authenticate"
  get  "/signup"          => "users#new"
  get  "/logout"          => "users#logout"
  get  "/password"        => "users#password"
  post "/password_update" => "users#password_update"
end

app/models/notepad.rb
class Notepad < ActiveRecord::Base
  belongs_to :user
end

app/controllers/notepads_controller.rb
class NotepadsController < ApplicationController
  before_action :set_notepad, only: [:show, :edit, :update, :destroy]

  # GET /notepads
  # GET /notepads.json
  def index
    @notepads = Notepad.all
  end

  # GET /notepads/1
  # GET /notepads/1.json
  def show
  end

  # GET /notepads/new
  def new
    @notepad = Notepad.new
  end

  # GET /notepads/1/edit
  def edit
  end

  # POST /notepads
  # POST /notepads.json
  def create
    @notepad = Notepad.new(notepad_params)

    respond_to do |format|
      if @notepad.save
        format.html { redirect_to @notepad, notice: 'Notepad was successfully created.' }
        format.json { render :show, status: :created, location: @notepad }
      else
        format.html { render :new }
        format.json { render json: @notepad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notepads/1
  # PATCH/PUT /notepads/1.json
  def update
    respond_to do |format|
      if @notepad.update(notepad_params)
        format.html { redirect_to @notepad, notice: 'Notepad was successfully updated.' }
        format.json { render :show, status: :ok, location: @notepad }
      else
        format.html { render :edit }
        format.json { render json: @notepad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notepads/1
  # DELETE /notepads/1.json
  def destroy
    @notepad.destroy
    respond_to do |format|
      format.html { redirect_to notepads_url, notice: 'Notepad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notepad
      @notepad = Notepad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notepad_params
      params.require(:notepad).permit(:name, :content_data, :user_id)
    end
end

app/helpers/notepads_helper.rb
module NotepadsHelper
end

app/views/notepads/_form.html.erb
<%= form_for(@notepad) do |f| %>
  <% if @notepad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notepad.errors.count, "error") %> prohibited this notepad from being saved:</h2>

      <ul>
      <% @notepad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field content_data_div">
    <%= f.label :content_data %><br>
    <%= f.text_area :content_data, width: '100000', heigth: '100%' %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notepads/edit.html.erb
<h1>Editing notepad</h1>

<%= render 'form' %>

<%= link_to 'Show', @notepad %> |
<%= link_to 'Back', notepads_path %>

app/views/notepads/index.html.erb
<h1>Listing notepads</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content data</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notepads.each do |notepad| %>
      <tr>
        <td><%= notepad.name %></td>
        <td><%= notepad.content_data %></td>
        <td><%= notepad.user %></td>
        <td><%= link_to 'Show', notepad %></td>
        <td><%= link_to 'Edit', edit_notepad_path(notepad) %></td>
        <td><%= link_to 'Destroy', notepad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notepad', new_notepad_path %>

app/views/notepads/new.html.erb
<h1>New notepad</h1>

<%= render 'form' %>

<%= link_to 'Back', notepads_path %>

app/views/notepads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @notepad.name %>
</p>

<p>
  <strong>Content data:</strong>
  <%= @notepad.content_data %>
</p>

<p>
  <strong>User:</strong>
  <%= @notepad.user %>
</p>

<%= link_to 'Edit', edit_notepad_path(@notepad) %> |
<%= link_to 'Back', notepads_path %>